#bypasspermission ^= players that have these permissions wont get any cooldowns.
items:
  ENDER_PEARL:
    cooldown: 10
    message: '<aqua>You must wait #SECONDS# seconds before you can teleport again.'
    bypasspermissions: itemcooldown.enderpearl
  GOLDEN_APPLE:
    cooldown: 5
    message: '<aqua>You must wait #SECONDS# seconds before you can teleport again.'
    bypasspermissions: itemcooldown.goldenapple